### ISSUE TITLE
Test data not available to the public

### ISSUE THREAD

**Issue by pgarrison** [bioio-devs/bioio-ome-zarr#14]
The test data for `test_reader.py` is not publicly available, so users outside our organization cannot run the tests.

I also don't have authorization.

**Comment by SeanLeRoy** [comment]
Duplicate of this one, but for another repo
https://github.com/bioio-devs/bioio-tifffile/issues/16

**Comment by BrianWhitneyAI** [comment]
Going to close this since its a duplicate
