### ISSUE TITLE
PR from a fork fails CI

### ISSUE THREAD

**Issue by pgarrison** [bioio-devs/bioio-ome-zarr#16]
I opened a PR and hoped that even though I don't have permissions to download the test data, maybe the CI job would be able to run the tests for me. Instead, the [github action](https://github.com/bioio-devs/bioio-ome-zarr/actions/runs/8666360380) also had an authentication issue.

```
Run aws-actions/configure-aws-credentials@v4
  with:
    role-to-assume: arn:aws:iam::978220035532:role/bioio_github
    role-session-name: bioio-lif-5a500dfce0a2661d3141369df3de968efc769829
    aws-region: us-west-2
    audience: sts.amazonaws.com
  env:
    BUCKET_NAME: bioio-dev-test-resources
    AWS_REGION: us-west-2
It looks like you might be trying to authenticate with OIDC. Did you mean to set the `id-token` permission? If you are not trying to authenticate with OIDC and the action is working successfully, you can ignore this message.
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

**Comment by toloudis** [comment]
Another data point:
Previously run actions worked (4 days prior) with OIDC authentication:
```
Assuming role with OIDC
Authenticated as assumedRoleId AROA6HQTVFXGGP4HAE5W3:bioio-lif-964a301b04e07b8d88957df46a836b8dc792ca66
```

**Comment by toloudis** [comment]
(bioio-lif looks fishy there, as it looks like a name from a different repo)

**Comment by pgarrison** [comment]
Update: resolved by getting myself added to `bioio-devs` and making the PR not from a fork. This will continue to be an issue for external contributors.

**Comment by toloudis** [comment]
We might have to meet up to discuss what to do about this, so that we can enable third party contributions.

**Comment by evamaxfield** [comment]
Whenever y'all have a discussion around this, happy to help test whatever you want locally and avoid running CI jobs en-masse because I don't have access to even download the test files locally to my dev machine 🙃

**Comment by SeanLeRoy** [comment]
Pretty much same thing as this and the another one in this same repo, need discussion about making test files public or at a minimum easier to run by contributors:
https://github.com/bioio-devs/bioio-tifffile/issues/16

**Comment by SeanLeRoy** [comment]
See #14 , closing this one as a duplciate
