### ISSUE TITLE
Latest `bioio-ome-zarr` and latest `bioio` have conflicting dependencies.

### ISSUE THREAD

**Issue by pgarrison** [bioio-devs/bioio-ome-zarr#28]
### Describe the Bug

bioio has the following requirement:
```
  # this pin <2.18.0 should be temporary and is maybe related to https://github.com/zarr-developers/zarr-python/issues/1891
  "zarr>=2.6.0,<2.18.0",
```

But bioio-ome-zarr has the following:
```
"zarr>=2.18.2",
```

### Solution
Until https://github.com/bioio-devs/bioio/issues/53 is resolved, `bioio-ome-zarr`'s requirement should be loosened to allow older `zarr` versions.

### Current workaround
Because I need to use the latest `bioio-ome-zarr`, I am currently trying to use bioio @ v1.0.2 and bioio-ome-zarr @ v1.1.0

**Comment by SeanLeRoy** [comment]
See https://github.com/bioio-devs/bioio/issues/53

**Comment by SeanLeRoy** [comment]
This is fixed as of now
